version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: carmabackend-api:v1
    container_name: carma_api
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app                    # ✅ on monte tout le projet
      - /app/node_modules         # ✅ prévient les conflits node_modules (Windows)
    environment:
      - NODE_ENV=development
    command: sh -c "sleep 5 && npm start"

  postgres:
    image: postgres:15
    container_name: postgres_carma_BDD
    restart: always
    ports:
      - "5466:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: carma
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
